### ISSUE TITLE
psd_native refers to Compose::DEFAULT_OPTS, but this is gone in latest version

### ISSUE THREAD

**Issue by chrisseaton** [layervault/psd_native#5]
I'm not very knowledgeable about Gems and dependencies, but I think psd_native will happily use any version of psd.rb above 2.1.1 and Compose::DEFAULT_OPTS is gone in the latest version. I was seeing this failure when using 3.2.2:

```
Failures:

  1) Image Exporting Renderer produces a correct PNG
     Failure/Error: expect(psd.tree.to_png).to be_an_instance_of(ChunkyPNG::Canvas)
     NameError:
       uninitialized constant PSD::Compose::DEFAULT_OPTS
     # ./lib/psd_native/compose.rb:15:in `do_blend'
     # ./lib/psd_native/compose.rb:8:in `block (2 levels) in <module:Compose>'
     # ./spec/image_spec.rb:56:in `block (3 levels) in <top (required)>'
```
